"use client";
import { motion } from "framer-motion";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function MedicalDisclaimerPage() {
  const fadeUpVariant = {
    hidden: { opacity: 0, y: 30 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6 } },
  };

  return (
    <div className="min-h-screen bg-gray-50 mt-12">
      {/* Hero Section */}
      <section className="bg-scanova-gradient text-white py-20">
        <div className="max-w-7xl mx-auto px-4">
          <motion.div
            variants={fadeUpVariant}
            initial="hidden"
            animate="visible"
            className="text-center"
          >
            <h1 className="text-4xl md:text-5xl font-bold mb-6">
              Medical Disclaimer
            </h1>
            <p className="text-xl text-white/90 mb-8 max-w-3xl mx-auto">
              The information, services, and reports provided by Scanova
              Diagnostics are for diagnostic purposes only and should not be
              considered as a substitute for professional medical advice,
              diagnosis, or treatment.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Content Section */}
      <section className="py-20 bg-white">
        <div className="max-w-5xl mx-auto px-4 space-y-12">
          <motion.div
            variants={fadeUpVariant}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            <h2 className="text-2xl font-bold text-scanova-text-header mb-4">
              1. No Substitute for Medical Advice
            </h2>
            <p className="text-scanova-text-body leading-relaxed">
              All test results and reports generated by Scanova Diagnostics are
              intended to support your healthcare journey. They should not be
              interpreted as medical advice. Patients must consult a qualified
              physician for interpretation of results and guidance on further
              treatment or management.
            </p>
          </motion.div>

          <motion.div
            variants={fadeUpVariant}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            <h2 className="text-2xl font-bold text-scanova-text-header mb-4">
              2. Limitations of Diagnostic Tests
            </h2>
            <p className="text-scanova-text-body leading-relaxed">
              Diagnostic tests have inherent limitations, and no single test can
              guarantee complete accuracy. Results should be reviewed in
              conjunction with medical history, physical examination, and advice
              from a licensed healthcare professional.
            </p>
          </motion.div>

          <motion.div
            variants={fadeUpVariant}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            <h2 className="text-2xl font-bold text-scanova-text-header mb-4">
              3. Patient Responsibility
            </h2>
            <ul className="list-disc list-inside text-scanova-text-body space-y-2">
              <li>
                Patients are responsible for providing accurate and complete
                medical history at the time of testing.
              </li>
              <li>
                Reports must not be used for self-diagnosis or self-treatment.
              </li>
              <li>
                Patients should immediately seek medical attention if they
                experience concerning symptoms, regardless of test outcomes.
              </li>
            </ul>
          </motion.div>

          <motion.div
            variants={fadeUpVariant}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            <h2 className="text-2xl font-bold text-scanova-text-header mb-4">
              4. External Links & Content
            </h2>
            <p className="text-scanova-text-body leading-relaxed">
              Our website may provide links to third-party health resources for
              educational purposes. Scanova Diagnostics does not endorse or
              guarantee the accuracy of such external content and is not
              responsible for its use.
            </p>
          </motion.div>

          <motion.div
            variants={fadeUpVariant}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            <h2 className="text-2xl font-bold text-scanova-text-header mb-4">
              5. Limitation of Liability
            </h2>
            <p className="text-scanova-text-body leading-relaxed">
              Scanova Diagnostics, its staff, and partners shall not be held
              liable for any decision, delay, or outcome resulting from the
              interpretation or misuse of diagnostic information. Patients must
              seek proper medical consultation before making healthcare
              decisions.
            </p>
          </motion.div>

          <motion.div
            variants={fadeUpVariant}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            <h2 className="text-2xl font-bold text-scanova-text-header mb-4">
              6. Contact Us
            </h2>
            <p className="text-scanova-text-body leading-relaxed">
              If you have any concerns about this disclaimer or your medical
              reports, please contact us at:{" "}
              <span className="font-semibold text-scanova-primary">
                info@scanovadiagnostics.com
              </span>
            </p>
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-scanova-gradient text-white">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <motion.div
            variants={fadeUpVariant}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            <h2 className="text-3xl md:text-4xl font-bold mb-6">
              Your Health Matters
            </h2>
            <p className="text-xl text-white/90 mb-8">
              Reports from Scanova Diagnostics are designed to assist, not
              replace, your doctor’s expertise. Always consult your physician
              for personalized medical care.
            </p>
            <Button
              asChild
              size="lg"
              className="bg-white text-scanova-primary hover:bg-gray-100 px-8 py-4"
            >
              <Link href="/services">Book a Test</Link>
            </Button>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
